import type { Metadata, Viewport } from "next";
import "./globals.css";
import { RegistraSW } from "@/components/RegistraSW";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  manifest: "/manifest.json",
};

export const viewport: Viewport = {
  themeColor: "#F1F0EE",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="h-full flex flex-col">
        <RegistraSW />
        {children}
      </body>
    </html>
  );
}
